### ISSUE TITLE
HTTPS download? GPG signature? Anything?

### ISSUE THREAD

**Issue by oconnore** [msys2/msys2.github.io#10]
How do I download this safely?

**Comment by elieux** [comment]
You can see hashes in the [downloads section at SF.net](https://sourceforge.net/projects/msys2/files/Base/). I was going to suggest downloading using HTTPS from SF.net, but the mirrors don't seem to generally support HTTPS (you'd have to find such mirror manually, I guess).

**Comment by mkae** [comment]
Are the binaries distributed by this system digitally signed?

**Comment by elieux** [comment]
They're not. Getting signing certificates costs money/effort that's not very justified in light of the software being open-source with fairly easily reproducible builds (not [bit-to-bit reproducible](https://reproducible-builds.org), sadly).

I'm personally not opposed to signing binaries. (Alexey or Ray might be though.)

**Comment by mingwandroid** [comment]
We're not opposed I don't expect, I mean, what's to oppose (I suppose it's a bit of a nice money spinner for those signing authorities but whatever ..)

**Comment by mkae** [comment]
Signing done by Alexey's key. Okay, every user can inspect the web of trust before installing anything. Fine.

I guess all binary packages have checksums of some sort?

**Comment by elieux** [comment]
All packages have checksums. You can find out more at https://wiki.archlinux.org/index.php/Pacman/Package_signing.

**Comment by mkae** [comment]
Thanks for the info.
