### ISSUE TITLE
Add link/info for server sponsoring

### ISSUE THREAD

**Issue by lazka** [msys2/msys2.github.io#102]
We should link to the server sponsor. Ideas on how/where welcome.

@elieux

**Comment by Biswa96** [comment]
Bitcoin!? 🤑

**Comment by lazka** [comment]
No money involved here.

**Comment by naveen521kk** [comment]
Should be as simple as having their brand name and logo and attribute/link to them at the bottom of the page. Possibly they have better ideas for this?

**Comment by lazka** [comment]
To quote them:

> No specifics regarding the backlink, just link to https://appfleet.com/ in the places that make the most sense.

**Comment by naveen521kk** [comment]
I think having a link to them using their logo and brand in the left or right sidebar should look good if it's possible. Or it should be under `Donations` section on the homepage.

**Comment by Biswa96** [comment]
Ideas can be taken from archlinux.org and archlinuxarm.org. Those has some sponsor links.

**Comment by elieux** [comment]
With archlinux.org's limited responsivity, the sidebar works fine, but our template hides the sidebars below a certain width.

I scrolled through the homepage and I wouldn't like to interrupt the intro and installation parts. Somewhere around the Authors and Contributors / Donations part looks okay. I'd like to err on the side of caution and propose the following order:

1. Server sponsor: appfleet.com (+ logo if available)
2. Project authors and contributors
3. Donations (maybe revise if they're still appropriate)

**Comment by lazka** [comment]
Sounds good

**Comment by lazka** [comment]
Feedback welcome: #105
