### ISSUE TITLE
bash: command not found (Win10)

### ISSUE THREAD

**Issue by nezvers** [msys2/msys2.github.io#103]
I followed https://www.msys2.org/ getting started guide.
The very first command (pacman -Syu) gave an error. Even -h didn't work.
It wasn't mentioned but I added /usr/bin/ to PATH and somehow it worked and followed through the guide.
After restarting the shell no commands are working except `ls /usr/bin/`.
```bash: /usr/bin/packman.exe: No such file or directory```

**Comment by lazka** [comment]
It's called `pacman` and not `packman`
