### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by isapir** [msys2/msys2.github.io#11]
Hi,

I created a video tutorial in HD that shows how easy it is to install.  Not sure if you want to link/embed it, but if so, it's available at https://www.youtube.com/watch?v=soQHM8tDQEI

And I can create a pull request that will embed it if you guys approve.

Thanks for the great work on msys2!

Igal

**Comment by TwentyOneSolutions** [comment]
Feel free to embed, link, or ignore.  I'm closing the issue here.

**Comment by mingwandroid** [comment]
The video was a great idea, sorry for the slow feed back  if you used update-core instead then we could put it on the wiki as a link to a user contributed video.

**Comment by mingwandroid** [comment]
We need to update the site with that information too, obviously!

**Comment by TwentyOneSolutions** [comment]
Ray, I can re-do it with changes if needed, or create another one.  

Can you please clarify what you mean by "if you used update-core instead"?  Is `update-core` instead of `pacman --needed -Sy bash pacman pacman-mirrors msys2-runtime` or in addition to it?  (if in addition does it come before it?)

By "We need to update the site with that information too" I assume that you mean add `update-core` to https://msys2.github.io/ ?

**Comment by mingwandroid** [comment]
Yeah. That's right. Also a clear explanation of why the update needs to be done in two stages sometimes would be good. I can't remember if your video was completely clear on that!

Until next month my time is very limited too..

**Comment by TwentyOneSolutions** [comment]
my video isn't "completely clear on that" because I don't know why that is required ;)

it's a short video so I can re-do it with changes, but it'd be good if I understand a little better why that's needed.

**Comment by mingwandroid** [comment]
I would be inclined to put the video also on the SourceForge wiki rather than this site for now, probably ..

**Comment by TwentyOneSolutions** [comment]
fine by me -- whatever works!

it's just that it took me some time to understand what is MSYS2/MinGW-w64, and I figured that if I had watched a video like that it would clarify a bit.

the wiki starts with "MSYS2 is an independent rewrite of MSYS, based on modern Cygwin (POSIX compatibility layer) and MinGW-w64 with the aim of better interoperability with native Windows software."  which doesn't tell anything to anyone who is not familiar with MSYS in the first place.

something along the tag line from the IRC channel would be a much better opening: "MSYS2 is a Unix-like shell for Windows..."

**Comment by TwentyOneSolutions** [comment]
I created an updated video at https://youtu.be/pb6Yb819pF0

**Comment by elieux** [comment]
I liked your video, it seemed clear, understandable and to the point. Much thanks for the effort. Unfortunately, the update process has changed again. :/ If you ever make a new video, I'll be glad to feature it somewhere.

**Comment by isapir** [comment]
In general I don't mind creating a new one, but if it will take a year from the point I publish it until it's reviewed here then the process will likely change again, making the new video obsolete as well ;)

**Comment by elieux** [comment]
I'm sorry about that. I can't promise anything, this is still a purely volunteer-driven project (a bunch of us got swamped with work and/or personal stuff), but I plan to be a bit more involved this year. :)
