### ISSUE TITLE
can you add support for other terminals like alacritty

### ISSUE THREAD

**Issue by SymphonySimper** [msys2/msys2.github.io#115]

**Comment by SymphonySimper** [comment]
sorry my bad

**Comment by Biswa96** [comment]
So, what conclusion did you reach finally?

**Comment by SymphonySimper** [comment]
It works with alacritty. Usually wsl programs run with their own bashrc. I thought so this did not work with alacirtty as there was no visual feedback ( like change in PS1). It just was my lack of knowledge. (sorry my english is sub par)
