### ISSUE TITLE
How do you run a commit to github from mysy2?

### ISSUE THREAD

**Issue by Meister-anon** [msys2/msys2.github.io#117]
I've already input git add & git commit.
I've made my title/message but I can't find what command to actually make it do the commit.

**Comment by canoshiz** [comment]
If you have your repository properly configured, all you'd need to do is `git push origin <branch>`, where *branch* is the branch to commit the changes to.

**Comment by Meister-anon** [comment]
Thanks for quickly getting back to me, I'll try that for my next commit.

**Comment by Meister-anon** [comment]
tried it and all I'm getting is this
bash: syntax error near unexpected token `newline'

**Comment by lazka** [comment]
> bash: syntax error near unexpected token `newline'

that suggests you didn't replace the `<branch>` part as noted above.

anyway, since this is old, I'm closing this,
