### ISSUE TITLE
Execution failed (unexpected exit code: -1073741819)

### ISSUE THREAD

**Issue by efa** [msys2/msys2.github.io#124]
I used the last installer:
msys2-x86_64-20210419.exe
on Win7 64 bit, with prev installation removed.

While installing I got this error:
```
Errore durante il processo di installazione (com.msys2.root.base):
Esecuzione non riuscita (codice di uscita imprevisto: -1073741819): "D:\ProgramFiles\msys64\usr\bin\bash.exe --login -c exit"
```
see the attached image:
![MSYS2_installError](https://user-images.githubusercontent.com/1578980/117635692-58485e00-b180-11eb-85a4-23334728ca13.png)
that in English is something like:
```
Error during the installation process (com.msys2.root.base):
Execution failed (unexpected exit code: -1073741819): "D:\ProgramFiles\msys64\usr\bin\bash.exe --login -c exit"
```
Them I hit Ignore, and installation finish, but clicking MSYS2 icon, open a black command window for a second than it close.

If I run the bash directly I got this message and nothing more:
```
D:\ProgramFiles\msys64\usr\bin>bash.exe
      0 [main] bash (8912) shared_info::initialize: size of shared memory region changed from 56248 to 40888
```

**Comment by efa** [comment]
I tryed to remove and reinstall, same error. I'm stuck without MSYS2, while before worked on this system, please help

**Comment by efa** [comment]
yes understand.

I had a working MSYS2 on Win7, first on update I got the error:
`signature from "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" is invalid`
but the suggested fix won't work as:
`pacman-key --populate msys2`
end, but then:
`pacman -Suy`
give error:
`error: key "" could not be looked up remotely`
Then I googled and found suggestion to use:
`$ pacman-key --refresh-keys`

but I got many:
`ERROR: A specified local key could not be updated from a keyserver`

Googling again I found:
https://bbs.archlinux.org/viewtopic.php?id=226770
to set
`SigLevel    = Never`
in
`/etc/pacman.conf`
and this work.

Then it update all, but left me with a won't running MSYS2.
So I de-installed my 6 GB installation and re-installed 350 MB base system, but go this new install error.

Cygwin fully updated on same system work. Maybe a conflict between the two?

**Comment by efa** [comment]
is Win7 still supported by MSYS2?

**Comment by efa** [comment]
solved. Running:
$ taskkill /f /fi "MODULES eq msys-2.0.dll"
then re-install work

**Comment by Biswa96** [comment]
> is there a command to save the list of installed packages?

`pacman -Qq`

**Comment by efa** [comment]
on Arch there is:
`yay -S --needed --noconfirm - < ~/packages.txt`
but not on MSYS2. Is there an alternative?

**Comment by Biswa96** [comment]
You have asked for the list of installed packages. That command is to install packages from a list or text file.

**Comment by efa** [comment]
I was able to recover my prev installation, with data and packages, and fully update it.
Then I saved packages list for future as backup.
THANK YOU for support

**Comment by yulisar** [comment]
> 
> 
> solved. From news of 2020-05-22, running:
> $ taskkill /f /fi "MODULES eq msys-2.0.dll"
> then re-install work

Since the process was quite many running, so I restart the windows 10 then run again the ridk. And Solved.

**Comment by lazka** [comment]
glad you got it working again. closing then.
