### ISSUE TITLE
ncursesw suport

### ISSUE THREAD

**Issue by Vm900** [msys2/msys2.github.io#125]
Hi,
How do i install ncurses with wide character support.It seems your repos don't have it.Can anyone help?
Thanks

**Comment by jeremyd2019** [comment]
It looks like libncursesw is in the mingw-w64-ncurses package:
https://packages.msys2.org/package/mingw-w64-x86_64-ncurses?repo=mingw64
In the files section is `libncursesw.a`

**Comment by Vm900** [comment]
Thank you
