### ISSUE TITLE
Wiki should move away from SF...

### ISSUE THREAD

**Issue by mkae** [msys2/msys2.github.io#13]
... for obvious reasons, but also to avoid scaring away potential new users. See also: https://github.com/msys2/msys2.github.io/issues/9

**Comment by mkae** [comment]
Correction for issue title:

   note  ->  move

XT9 interfering there!
:-(

**Comment by achadwick** [comment]
The issue title can be edited by its creator, I think. @mkae - perhaps when you're not using a mobile device?

**Comment by pedro7** [comment]
Hello all, and @Alexpux and @martell,
Is this ["Migrate Wiki from SF to Github"] a valid task?
If so, In which project shall this be, for job tracking purposes?

Thanks!

**Comment by mkae** [comment]
This isn't an official task whatsoever, yet.

Ressources are missing to get that task done.

**Comment by elieux** [comment]
Done! https;//github.com/msys2/msys2/wiki
