### ISSUE TITLE
[Question] what is the license for stylesheets/extra.css?

### ISSUE THREAD

**Issue by eranif** [msys2/msys2.github.io#130]
A quick question: what is the license for the `stylesheets/extra.css` file ? I really like the documentation theme and would like to use it for my open source project: https://docs.codelite.org (a GitHub project, GPLv2 licensed: https://github.com/eranif/codelite)

**Comment by lazka** [comment]
Good question. I'm the author of the CSS. The images come from our old website which used https://github.com/pages-themes/tactile and is CC0

Feel free to use the CSS under any open source license you want.

**Comment by Biswa96** [comment]
Shouldn't the license and the author be mentioned in source code to respect the work?

**Comment by eranif** [comment]
thank you!

**Comment by lazka** [comment]
> Shouldn't the license and the author be mentioned in source code to respect the work?

depends on the license

**Comment by Biswa96** [comment]
So, we are now driven by the laws and licesenses instead of a simple appreciation of someone's hard work 😟
