### ISSUE TITLE
What is MSYS2 license?

### ISSUE THREAD

**Issue by MariuszCwikla** [msys2/msys2.github.io#132]
Hello,
what is license for MSYS2 itself? I see https://github.com/msys2/MINGW-packages has BSD-3 license,
but I can't find license for MSYS2 as a whole, neither here nor on the website.
My company requires that I provide license for the software before I can install it.

**Comment by lazka** [comment]
There is now a license page: https://www.msys2.org/license/

If the license of any particular part of MSYS2 needs more clarification please tell us.
