### ISSUE TITLE
Could not resolve host: mirror.yandex.ru

### ISSUE THREAD

**Issue by ujos** [msys2/msys2.github.io#143]
Is there a way to remove the `mirror.yandex.ru`  host from the mirrors list? I live in Ukraine and yandex.ru is blocked here.

```
dmitr@Lenovo MINGW64 ~
$ pacman -Sy
:: Synchronizing package databases...
 mingw32              1218.0 KiB   166 KiB/s 00:07 [#####################] 100%
 mingw64              1224.1 KiB   113 KiB/s 00:11 [#####################] 100%
 ucrt64               1468.7 KiB   177 KiB/s 00:08 [#####################] 100%
 clang64              1154.8 KiB   181 KiB/s 00:06 [#####################] 100%
 msys is up to date
error: failed retrieving file 'ucrt64.db' from mirror.msys2.org : Could not resolve host: mirror.yandex.ru
warning: too many errors from mirror.msys2.org, skipping for the remainder of this transaction
error: failed retrieving file 'clang64.db' from mirror.msys2.org : Could not resolve host: mirror.yandex.ru
```

**Comment by Biswa96** [comment]
Try this. Go to `/etc/pacman.d` folder. Edit every mirrorlist file by commenting out the mirror.msys2.org and the blocked ones. Here are the other mirrors as referenc https://github.com/msys2/MSYS2-packages/blob/master/pacman-mirrors/mirrorlist.mingw

**Comment by lazka** [comment]
I've created https://github.com/msys2/msys2-main-server/issues/9 as well

**Comment by ujos** [comment]
> Go to /etc/pacman.d folder. Edit every mirrorlist file by commenting out the mirror.msys2.org 

It works now. Thank you very much!

**Comment by lazka** [comment]
Closing in favor of https://github.com/msys2/msys2-main-server/issues/9
