### ISSUE TITLE
signature from "David Macek <david.macek.0@gmail.com>" is unknown trust

### ISSUE THREAD

**Issue by iklingen** [msys2/msys2.github.io#145]
Hi All.

Today I was not been able to update my MSYS2 instance. After `pacman -Suy` command I got the following questions for many packages:
```
error: autoconf: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/autoconf-2.71-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
error: autoconf2.13: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/autoconf2.13-2.13-3-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
```
This case is very similar to #2343 and #2033.

Thank you!

**Comment by dfnewell** [comment]
Wanted to throw my hat in to note this still appears to be happening.

**Comment by lazka** [comment]
This was usually when the package key expired and wasn't refreshed soon enough (or it was forgotten to be re-newed by the maintainer).

The "solution" is now documented here: https://www.msys2.org/docs/updating/#potential-issues
