### ISSUE TITLE
Installation on Windows 11 stuck at 66%

### ISSUE THREAD

**Issue by hollowknight** [msys2/msys2.github.io#146]
Installation of 20120604 release on Windows 11 Pro OS Build 22000.100 stuck at 66%

Preparing the installation...

Installing component MSYS2 64bit base
Extracting "20210604msys64.7z"

**Comment by MPagliari** [comment]
Yes, my bad That was the issue. Disabled Avast antivirus and worked fine.

**Comment by Biswa96** [comment]
Can anyone make sure if the above workaround work? If yes the issue can be closed.

**Comment by lazka** [comment]
no response, so closing.
