### ISSUE TITLE
[after new release] Change upgrade steps

### ISSUE THREAD

**Issue by elieux** [msys2/msys2.github.io#15]
After a release with pacman 5.0.1.6403 (or newer) is uploaded, we should change the upgrade steps on the website to just call `pacman -Syu` twice. It'd be also nice to update the screenshots.

**Comment by okonomiyaki3000** [comment]
:+1:

**Comment by achadwick** [comment]
Is this now due, since msys2-*-20160921.exe have been linked? If it's no longer relevant, please close.
