### ISSUE TITLE
New mirror request [China]

### ISSUE THREAD

**Issue by d-w-x** [msys2/msys2.github.io#155]
Would you please add new mirror in mirror list and the config files?

---
mirror info:

- url: mirror.nju.edu.cn/msys2
- protocol: http, https, rsync
- Synchronization frequency: every day
- Bandwidth: 10Gb/s
- Location: Nanjing, China, Asia
- Contact: my@yaoge123.com

**Comment by lazka** [comment]
thanks!

**Comment by lazka** [comment]
Added to the docs, the pacman mirror list and our mirrorbits server:

* https://github.com/msys2/msys2.github.io/commit/bfc24208e34eb2006770b9949e3e6ad9aeadacbe
* https://github.com/msys2/MSYS2-packages/pull/2627
* https://github.com/msys2/msys2-main-server/commit/fe856f504befa04c4c41ae2f0edd129b4b7a467d -> https://mirror.msys2.org/?mirrorstats

thanks

**Comment by lazka** [comment]
@d-w-x the mirror is down for 14 days now. Will it come back?

**Comment by d-w-x** [comment]
Yes, for some known issues in China, the server can't connect until 10.24.

**Comment by lazka** [comment]
ok, thanks for the info :)

**Comment by d-w-x** [comment]
Just now, I test out that some of mirror sites from Chine (hosted by university) can't connect maybe for the same reason, including:

- https://mirrors.hit.edu.cn/msys2/
- https://mirrors.sjtug.sjtu.edu.cn/msys2/

and [aliyun mirror](https://mirrors.aliyun.com/msys2/) has stopped sync for some days.

They mostly are healthy in their school, maybe those site status should be tested after some days.

**Comment by d-w-x** [comment]
Update, recovered:
- https://mirror.nju.edu.cn/msys2/
- https://mirrors.sjtug.sjtu.edu.cn/msys2/

**Comment by lazka** [comment]
confirmed, thanks!
