### ISSUE TITLE
i686 installer does not work on Pentium III CPU PC running Windows XP.

### ISSUE THREAD

**Issue by konstunn** [msys2/msys2.github.io#16]
It gives an error message and offers to send a report to MS.

**Comment by mingwandroid** [comment]
The installer needs a newer CPU.  Can you use the tar.xz instead. You won't be able to use various software though, like  Qt stuff.

**Comment by konstunn** [comment]
Thank you for your fast response. I have managed to download, extract and configure the package, though it wasn't easy on my old system.
