### ISSUE TITLE
/usr/bin/pacman: Permission denied after initial pacman -Syu

### ISSUE THREAD

**Issue by Tomblarom** [msys2/msys2.github.io#168]
I used this official guide from [msys2.org](https://www.msys2.org/) to install MSYS2. Unfortunately I'm not able to proceed with any further steps of this guide. Sucessfully run `pacman -Syu` and terminated the terminal:
![2021-11-23 14_05_57-~](https://user-images.githubusercontent.com/12703270/143031368-031748ef-3b51-4935-8cdb-80fa2657a654.png)

After that I'm not able to use `pacman` again:
![2021-11-23 14_06_39-~](https://user-images.githubusercontent.com/12703270/143031384-66fc3b25-6ad9-4828-b9cd-a4d52d9be3ee.png)

I already tried:

- reinstalling and rebooting
- running the setup and console as admin
- Removing the lockfile with `rm -f /var/lib/pacman/db.lck`

***

**OS:** Windows 10 - 2004 (19041.1288)
**Setup:** msys2-x86_64-20210725.exe

**Comment by Biswa96** [comment]
Make sure that there is no antimalware or antivirus program including Windows Defender is blocking the process.

**Comment by Tomblarom** [comment]
@Biswa96 which file should I watch out for? Yes I'm in a work environment and we use Cisco Secure Endpoint, but are you sure that's related?

**Comment by lazka** [comment]
For such trigger happy scanners it's usually best to exclude the whole MSYS2 directory.

**Comment by Tomblarom** [comment]
Used an excluded folder and it seems, that it's not blocking anymore.

**Comment by lazka** [comment]
Closing in favor of #199
