### ISSUE TITLE
Checksums off

### ISSUE THREAD

**Issue by hkmix** [msys2/msys2.github.io#17]
I downloaded the 64-bit version twice and got the same checksum both times: `9cd2dce9b96dce58e87ac2dfaa0cfcf86bbbfad3`. Does the web page need to be updated?

**Comment by elieux** [comment]
No. You computed the SHA1 checksum. The webpage shows SHA256 checksums.

**Comment by elieux** [comment]
No reaction, closing. Reopen if neede.
