### ISSUE TITLE
sizeof void * is 8 bytes, but long integer is 4 bytes, why not 8 bytes in 64 bits windows OS?

### ISSUE THREAD

**Issue by MichaelShu3333** [msys2/msys2.github.io#170]
I test long integer size , I find sizeof void * is 8 bytes, but long integer is 4 bytes, why not 8 bytes in 64 bits windows OS?
This is not equal in linux or windows 64 bits OS.

**Comment by Biswa96** [comment]
That is default types in Windows environment. You can find more information here https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models

**Comment by MichaelShu3333** [comment]
thx
