### ISSUE TITLE
Mirror application， Alibaba Cloud

### ISSUE THREAD

**Issue by hjadb** [msys2/msys2.github.io#171]
This issue is that we expect to add our mirror into your mirror list. https://www.msys2.org/dev/mirrors/. Please refer to the following information.
1. Country: CN
2. Site Name: Alibaba Cloud
3. Mirror Name: mirrors.aliyun.com
4. Categories: http(http://mirrors.aliyun.com/msys2/), https (https://mirrors.aliyun.com/msys2/).
5. Bandwidth: 10000
6. Internet2: No
7. Email: ali-yum@alibaba-inc.com
8. Comments: First mirror site from cloud service provider in China, speedup with CDN services.

**Comment by lazka** [comment]
Thank you.

Do you also have rsync support?

**Comment by hjadb** [comment]
Sorry, we don't offer Rsync service

**Comment by lazka** [comment]
ok, thanks

**Comment by lazka** [comment]
done. Thanks!
