### ISSUE TITLE
new mirror request: mirrors.hit.edu.cn/msys2

### ISSUE THREAD

**Issue by Logiase** [msys2/msys2.github.io#180]
`mirrors.hit.edu.cn/msys2` 

- supports HTTP, HTTPS and rsync
- theoretical bandwidth 20Gbps
- sync every 2 hour
- location Harbin, China, Asia

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
Done

**Comment by lazka** [comment]
@Logiase Hey, mirrors.hit.edu.cn has been offline for two weeks now. Do you have any information on if/when it will come back?

**Comment by Logiase** [comment]
@lazka Hi, the mirror site is located in China, there is always some strange problems caused by the GOV and policies. Now the mirror site is still running, but blocking some connections. 

Please remove this mirror site until it returns to normal. I'm very sorry and I can do nothing for now. 😢
