### ISSUE TITLE
mirror.clarkson.edu updates

### ISSUE THREAD

**Issue by Alextopher** [msys2/msys2.github.io#185]
I'm one of the current volunteer maintainers of the [mirror.clarkson.edu](https://mirror.clarkson.edu) site. We've made some changes since we first started hosting msys2.

**New mirror contact email**: mirroradmin -at- clarkson.edu
**Upgraded internet connections**: Theoretical 2 gigabit upload and maximum measured in the last 30 days is 1.73 gbit/s. 

Does this mean we can become a Tier 1 mirror?

Feel free to let me know if there is anything else we can do for msys2 :)

**Comment by lazka** [comment]
Thanks!

For context, we removed it from the tier 1 pool when blender 3 was released, which seemed to saturate the mirror (according to your stats) and to some of our users complaining.

I'll add it back :)

**Comment by lazka** [comment]
All restored:

* https://github.com/msys2/MSYS2-packages/commit/f1200895207378bb
* https://github.com/msys2/msys2.github.io/commit/7cee8534697a3a8
* https://github.com/msys2/msys2-main-server/commit/79c0116750860214baccb

Thanks

**Comment by Alextopher** [comment]
> For context, we removed it from the tier 1 pool when blender 3 was released

Sorry about that. The Blender 3.0 was huge news and broke things. We made Blender aware of the issue and actually requested a change made to their mirror system. Previously we were the fallback mirror if there was no mirror in your country or continent, now it's chosen randomly from the pool of mirrors. We also recommended they find a Mirror in Asia to support the project and they now have one ! https://mirrors.aliyun.com/blender/

Blender 3.1 releases March 9th. It should go a lot smoother than the 3.0 release 🤞. If not I think we're willing to throttle blender downloads, we'll be watching it closely.

**Comment by lazka** [comment]
Good to know, thanks!

**Comment by lazka** [comment]
@Alextopher hey, we had an outage 9 days ago and since then the mirror doesn't seem to sync anymore

**Comment by Alextopher** [comment]
I've forwarded this to the new maintainers! Thanks

**Comment by lazka** [comment]
Ah, good to know, I'll use the email next time. thanks

**Comment by lavajuno** [comment]
Thank you for bringing this to our attention @Alextopher. Poking around now to see what's going on.

**Comment by lazka** [comment]
It seems to be fixed now, thanks!

**Comment by lazka** [comment]
@lavajuno looks like rsync is down/unreachable (at least for two days):

```
$ rsync --contimeout 5 rsync://mirror.clarkson.edu
rsync error: timeout waiting for daemon connection (code 35) at socket.c(278) [Receiver=3.3.0]
```

**Comment by lavajuno** [comment]
Oh dear, this is a very interesting time (finals week) for that to happen. I'll see what I can do tonight and update you asap.

**Comment by lazka** [comment]
It can wait :) thanks

**Comment by lavajuno** [comment]
Apologies for the wait, rsync service should be back up now. Feel free to poke me if you have any issues.

**Comment by lazka** [comment]
fyi, looks like the mirror stopped syncing 4 days ago.

**Comment by aHalliday13** [comment]
Apologies for such a long delay, I'm one of the current maintainers for mirror.clarkson.edu. msys2 should be syncing regularly again. If you have any issues in the future feel free to contact mirroradmin at clarkson dot edu or any of the lab directors listed [here](https://cosi.clarkson.edu/contact.html). Thanks!
