### ISSUE TITLE
Apps Stalling

### ISSUE THREAD

**Issue by okonomiyaki3000** [msys2/msys2.github.io#19]
I'm having a very weird issue with some apps. So far it seems to affect vim and ssh but it's not necessarily limited to them. It's a bit hard to explain but, for example, when I open vim, my terminal is just blank. If I hit `esc` several times, my document will finally appear. Seems to be totally unresponsive though so I'd like to quit. I type `:q<enter>` but again nothing happens until I hit `esc` a few times and one-by-one the characters I had typed appear and finally vim exits. Same thin in ssh. So yeah, essentially unusable.

**Comment by Alexpux** [comment]
Look at latest cygwin mailing list. This is due to last changes in cygwin. Will be fixed later when they fix it

**Comment by okonomiyaki3000** [comment]
Great. Is there a way I can downgrade until then?

**Comment by Alexpux** [comment]
Don't think it possible because many applications are linked with new runtime that have new symbols. You will get lots of errors

**Comment by okonomiyaki3000** [comment]
Well, this is most unfortunate. How does such a change make it into a shipping product? I haven't found the mailing list item that mentions it or I don't know what to look for but do they have an eta for a fix?

**Comment by Alexpux** [comment]
Maybe this https://cygwin.com/ml/cygwin/2016-04/msg00126.html

**Comment by okonomiyaki3000** [comment]
Thanks. The followup message to that says that some code had been reverted to fix it. Should we expect that fix soon?

**Comment by Alexpux** [comment]
On next week I think. Not sooner

**Comment by okonomiyaki3000** [comment]
Got it. Thanks.

**Comment by okonomiyaki3000** [comment]
The latest update fixed it. Thanks!
