### ISSUE TITLE
New mirror Kentucky USA

### ISSUE THREAD

**Issue by arclight2020** [msys2/msys2.github.io#196]
New mirror setup complete, 
Location Kentucky, USA
Support Contact: support@sandyriver.net
Connection: 1 Gbit/s (will be upgrading to 20Gbit/s once new switch is installed ) 
Synced hourly via sync script to rsync://repo.msys2.org/builds/ 

Accessible via https,rsync,http,anon-ftp
https://mirror2.sandyriver.net/pub/software/msys2/
rsync://mirror2.sandyriver.net/pub/software/msys2/
ftp://mirror2.sandyriver.net/pub/software/msys2/
http://mirror2.sandyriver.net/pub/software/msys2/

**Comment by lazka** [comment]
Thanks

**Comment by lazka** [comment]
Added to mirrorbits for starters: https://github.com/msys2/msys2-main-server/commit/e839acc9aaeafdffd5

**Comment by lazka** [comment]
Add everywhere else now as well.
