### ISSUE TITLE
Who Is Using MSYS2 - adding one more project.

### ISSUE THREAD

**Issue by SDX-LV** [msys2/msys2.github.io#198]
Could some admin please add one more entry to the "[Who Is Using MSYS2](https://www.msys2.org/docs/who-is-using-msys2/)" without creating a fork?

[Mesh2HRTF](https://mesh2hrtf.sourceforge.io) uses MSYS2 for its Windows NumCalc [binaries](https://sourceforge.net/p/mesh2hrtf-tools/code/ci/master/tree/NumCalc_WindowsExe/) ([Documentation](https://sourceforge.net/p/mesh2hrtf/wiki/Installation_2/#compiling-numcalc-on-windows-using-msys2)).

`[Mesh2HRTF](https://mesh2hrtf.sourceforge.io) uses MSYS2 for its Windows NumCalc [binaries](https://sourceforge.net/p/mesh2hrtf-tools/code/ci/master/tree/NumCalc_WindowsExe/) ([Documentation](https://sourceforge.net/p/mesh2hrtf/wiki/Installation_2/#compiling-numcalc-on-windows-using-msys2)).`

**Comment by Biswa96** [comment]
Feel free to create a pull request with that change. BTW, I can see only compiled executable in that project. Where is the source code? Is that project free and open source?

**Comment by SDX-LV** [comment]
Hi, the Mesh2HRTF project is of course open source (LGPL version 3.0): https://github.com/Any2HRTF/Mesh2HRTF/tree/develop/mesh2hrtf/NumCalc/Source 

I understand that it can be forked, but would be great if someone could add this one line of text without all the Pull request process :)

thanks!

**Comment by SDX-LV** [comment]
@lazka - thank you.
