### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by Legimet** [msys2/msys2.github.io#2]
The link for the exe download in step 1 should be http://sourceforge.net/projects/msys2/files/Base/x86_64/msys2-x86_64-20140704.exe/download.

**Comment by sascha-tasche** [comment]
SF says Error 404.
The project can not be found.

**Comment by mingwandroid** [comment]
SourceForge mirrors can be quite flaky. Works fine from where I'm sitting:

http://garr.dl.sourceforge.net/project/msys2/Base/i686/msys2-i686-20150202.exe
and
http://garr.dl.sourceforge.net/project/msys2/Base/x86_64/msys2-x86_64-20150202.exe
