### ISSUE TITLE
Question: "pacman -S mingw-w64-x86_64-make" does not install make or mingw64-make?

### ISSUE THREAD

**Issue by LowLevelMahn** [msys2/msys2.github.io#203]
im using the "MSYS2 MinGW x64" environment to compile a 200kLOC CMake project with the gcc
everything worked amazingly well out of the box - thanks msys2 community !

i've just installed msys2 + the mingw-w64 tools i needed
```
pacman -S mingw-w64-x86_64-toolchain
pacman -S mingw-w64-x86_64-cmake
pacman -S mingw-w64-x86_64-make
pacman -S mingw-w64-x86_64-ninja
```
starting with "MSYS2 MinGW x64" ,cmake, ninja or make - and it just worked - wow!

but i've got problems to understand why installing `mingw-w64-x86_64-make` gives me no `make` or a `mingw64-make` program but only `mingw32-make` (everything works with that) im just curious whats the reason for that

for all the other packages i get the "normal" named tools withouth the `mingw64-` prefix

**Comment by Biswa96** [comment]
You can find the reason why the program name is `mingw32-make` in this file https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-make/PKGBUILD.

BTW, the `mingw-w64-x86_64-` prefix is just a part of the package naming scheme. More at here https://www.msys2.org/docs/package-naming/. I think the name `mingw32-make` came from the target triplet:

```
$ gcc -dumpmachine
x86_64-w64-mingw32
```

**Comment by LowLevelMahn** [comment]
> You can find the reason why the program name is `mingw32-make` in this file https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-make/PKGBUILD.

so its definitily not bug - thanks for the description
