### ISSUE TITLE
mirror.selfnet.de: Missing support for TLS 1.2

### ISSUE THREAD

**Issue by eur2fe** [msys2/msys2.github.io#204]
I am trying to run a `pacman -Syu`, and I am getting several different error messages, such as

```
$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 ucrt64 is up to date
 clang32 is up to date
 clang64 is up to date
 msys is up to date
error: failed retrieving file 'mingw64.db' from mirror.msys2.org : OpenSSL SSL_connect: Connection reset by peer in connection to mirror.selfnet.de:443
```

There were other error messages related to TLS 1.0 (which our corporate proxy may block?), I am not sure.

Accessing <https://mirror.selfnet.de/msys2/> in Edge/Chrome gives me

```
The connection for this site is not secure
mirror.selfnet.de uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

I remove the mirror from `/etc/pacman.d/mirrorlist.msys` and now it appears to work.

**Comment by lazka** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=mirror.selfnet.de&s=141.70.124.1 looks fine

Maybe a temporary issue?

**Comment by eur2fe** [comment]
> Maybe a temporary issue?

Unfortunately, not. I raised a ticket with our computer hotline and it turns out to be a well known problem: Our proxy server from Symantec/BroadCom does not support TLS 1.3, because their latest version supporting TLS 1.3 is broken.

Bummer!

**Comment by lazka** [comment]
Oh, they dropped TLS 1.2... hm I'll ask them if that was on purpose.

**Comment by lazka** [comment]
I've emailed them.

**Comment by lazka** [comment]
It's the only mirror we have that doesn't support TLS 1.2. I've disabled it on mirror.msys2.org for now.

**Comment by eur2fe** [comment]
Sounds good. Thank you!

**Comment by lazka** [comment]
I got no response so far, so I emailed them again.

**Comment by carrotIndustries** [comment]
mirrror.selfnet.de admin here, I've enabled TLS 1.2

**Comment by lazka** [comment]
@carrotIndustries thanks 🙏

re-enabled now
