### ISSUE TITLE
I want to install the odler gcc version (e.g. gcc10) on the newest msys2. how to ?

### ISSUE THREAD

**Issue by freelixilong** [msys2/msys2.github.io#205]
Our project is developed by the gcc-10, but it seems that the newest msys2 could only install the gcc-11 or gcc-12. How to install the older gcc?

Thanks

**Comment by Biswa96** [comment]
You have to manually download the package and install it with `pacman -U` command. Packages can be found here https://mirror.msys2.org/mingw/

**Comment by MehdiChinoune** [comment]
Did you try to build your project with gcc-11/gcc-12.

**Comment by freelixilong** [comment]
> You have to manually download the package and install it with `pacman -U` command. Packages can be found here https://mirror.msys2.org/mingw/

This may be a  solution.
