### ISSUE TITLE
New mirror in Taiwan

### ISSUE THREAD

**Issue by PingNote** [msys2/msys2.github.io#206]
Mirror domain name: mirror.archlinux.tw
Mirror IP: 125.228.118.224
Geographical location of the mirror (country): Taiwan

URLs for supported access methods (http(s), rsync):
* http://mirror.archlinux.tw/MSYS2/
* https://mirror.archlinux.tw/MSYS2/
* rsync://mirror.archlinux.tw/msys2/

mirror's available bandwidth: 250 Mbit/s
An administrative contact email: PingNote.Wu@gmail.com
An alternative administrative contact email: archlinux-tw-general@googlegroups.com

Synced hourly via systemd timer to rsync://repo.msys2.org/builds/

feel free to contact me if you need any information :)

**Comment by lazka** [comment]
Sorry for the delay, added now.

I added it as a tier 1 despite it being 250 Mbit/s because we don't have many mirrors there, well see if anyone complains..
