### ISSUE TITLE
Why mingw64 python pip not use wheels?

### ISSUE THREAD

**Issue by milen-prg** [msys2/msys2.github.io#218]
I use pip to install python packages, which are not in msys2 repositories. PIP from mingw64 terminal of msys2 always tries to use the package source and usually failed to build, WHY it not uses the prebuild wheels, which are in pypi repositories?

**Comment by Biswa96** [comment]
There are some issues mentioned here https://www.msys2.org/docs/python/

**Comment by milen-prg** [comment]
> There are some issues mentioned here https://www.msys2.org/docs/python/

Thank you, now I understand. 
I'm sorry for these issues in msys2 mingw64 python 😕
