### ISSUE TITLE
how to change language

### ISSUE THREAD

**Issue by stax76** [msys2/msys2.github.io#22]
Hello,

is it possible to change language from local language German to English?
```
Frank@DESKTOP-EBTU8L3 MSYS /
$ make
make: *** Es wurden keine Ziele angegeben und keine „make“-Steuerdatei gefunden.  Schluss.
```

**Comment by Alexpux** [comment]
````export LC_ALL=en_US.UTF-8````

**Comment by stax76** [comment]
awesome, thanks!

**Comment by dariomangoni** [comment]
`export LC_ALL="en_US.UTF-8"` applies the changes only on the current shell, am I right?
I don't know if there are any better places, but in order to make the change permanent I'm used to add `export LC_ALL="en_US.UTF-8"` to `C:\msys64\etc\profile`
