### ISSUE TITLE
error: failed retrieving file 'ucrt64.db' from mirror.msys2.org : SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by squercia** [msys2/msys2.github.io#224]
Hi, 

  I've read and tried many solutions to solve issue hereunder but unsuccessfully : 

error: failed retrieving file 'ucrt64.db' from mirror.msys2.org : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'clang32.db' from mirror.msys2.org : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'mingw32.db' from mirror.msys2.org : SSL certificate problem: unable to get local issuer certificate
warning: too many errors from mirror.msys2.org, skipping for the remainder of this transaction
error: failed retrieving file 'mingw64.db' from mirror.msys2.org : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'clang64.db' from mirror.msys2.org : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'ucrt64.db' from repo.msys2.org : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'clang32.db' from repo.msys2.org : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'mingw32.db' from repo.msys2.org : SSL certificate problem: unable to get local issuer certificate
warning: too many errors from repo.msys2.org, skipping for the remainder of this transaction
error: failed retrieving file 'mingw64.db' from repo.msys2.org : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'clang64.db' from repo.msys2.org : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'clang32.db' from mirror.umd.edu : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'mingw32.db' from mirror.umd.edu : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'mingw64.db' from mirror.umd.edu : SSL certificate problem: unable to get local issuer certificate
warning: too many errors from mirror.umd.edu, skipping for the remainder of this transaction
error: failed retrieving file 'clang64.db' from mirror.umd.edu : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'ucrt64.db' from mirror.umd.edu : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'clang32.db' from mirror.yandex.ru : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'mingw32.db' from mirror.yandex.ru : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'mingw64.db' from mirror.yandex.ru : SSL certificate problem: unable to get local issuer certificate
warning: too many errors from mirror.yandex.ru, skipping for the remainder of this transaction
error: failed retrieving file 'clang64.db' from mirror.yandex.ru : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'ucrt64.db' from mirror.yandex.ru : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'mingw32.db' from download.nus.edu.sg : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'mingw64.db' from download.nus.edu.sg : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'clang64.db' from download.nus.edu.sg : SSL certificate problem: unable to get local issuer certificate
warning: too many errors from download.nus.edu.sg, skipping for the remainder of this transaction
error: failed retrieving file 'clang32.db' from download.nus.edu.sg : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'mingw32.db' from ftp.acc.umu.se : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'mingw64.db' from ftp.acc.umu.se : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'clang64.db' from ftp.acc.umu.se : SSL certificate problem: unable to get local issuer certificate
warning: too many errors from ftp.acc.umu.se, skipping for the remainder of this transaction
error: failed retrieving file 'clang32.db' from ftp.acc.umu.se : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'ucrt64.db' from download.nus.edu.sg : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'clang64.db' from ftp.nluug.nl : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'mingw32.db' from ftp.nluug.nl : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'mingw64.db' from ftp.nluug.nl : SSL certificate problem: unable to get local issuer certificate
warning: too many errors from ftp.nluug.nl, skipping for the remainder of this transaction
error: failed retrieving file 'clang32.db' from ftp.nluug.nl : SSL certificate problem: unable to get local issuer certificate
error: failed retrieving file 'ucrt64.db' from ftp.nluug.nl : SSL certificate problem: unable to get local issuer certificate

  It happens when using pacman update.

  Could you please help me ?

  Thanks.

Sly

**Comment by squercia** [comment]
with pacman -Syuuu or Syy

Update is working but I've this output. I'd like to solve this issue please.

I'm using a proxy and I've the certificate ... Should I run more CLI to configure msys tool please ?

**Comment by squercia** [comment]
Thanks Iazkax, curl works but pacman updates still run with SSL errors.

**Comment by lazka** [comment]
Hm, weird.

**Comment by squercia** [comment]
Oh ! Wait Iazka, issue is solved :-) After running curl, pacman updates is running without SSL error messages. Thank you very much !

**Comment by lazka** [comment]
glad it helped
