### ISSUE TITLE
A nice written article that might help others gets included in the repo/site

### ISSUE THREAD

**Issue by FahimFBA** [msys2/msys2.github.io#236]
Hello,
I have written an article on [freeCodeCamp](https://www.freecodecamp.org/news/how-to-install-c-and-cpp-compiler-on-windows/) on how to install C and C++ compiler on Windows using MSYS2. A lot of people find that article pretty helpful. Therefore, I was thinking about sharing that here and asking you whether you would be interested in including that article here for others' benefit.

Thanks a lot for maintaining this repository. This is helping us a lot in installing the compilers on Windows.

**Comment by lazka** [comment]
External guides outside of our control will get outdated sooner or later and can't be updated by our community, so I'd rather like to see our documentation improved instead of linking to external guides.

I appreciate you spreading the word though and documenting your experience so thoroughly.
