### ISSUE TITLE
Where's the installer?

### ISSUE THREAD

**Issue by petsuter** [msys2/msys2.github.io#25]
The "MSys2 Installer" website points to a Github repository for source and issues with the website and another one for the packages, but where do I find the source and issues for the *installer*?

**Comment by mingwandroid** [comment]
It is based on the qt installer framework, with our own patches:
https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-qt-installer-framework

The scripts to put everything together are at:
https://github.com/Alexpux/MSYS2-packages/tree/master/msys2-installer

**Comment by petsuter** [comment]
Thanks. (I'd suggest mentioning this on the webpage, so it's clear where to report issues.) I was looking to report or find something about this: https://github.com/Alexpux/MSYS2-packages/issues/625
