### ISSUE TITLE
MSYS2-installation.md wrong sentence

### ISSUE THREAD

**Issue by pedrolcl** [msys2/msys2.github.io#252]
[wiki/MSYS2-installation.md](https://github.com/msys2/msys2.github.io/tree/source/web/wiki/MSYS2-installation.md) says:

> Note: if you are using 64-bit Windows, there is no reason to use 32-bit MSYS2. Well, to be honest, there is one reason: you want to develop MSYS2 software (or contribute to MSYS2-packages) and want to test that the software/package also works on 32-bit MSYS2. When it comes to native software, **64-bit MSYS2 can be used to build, install and run both 32-bit and 64-bit variants**. 64-bit MSYS2 software (practically speaking) never needs to be "re-based", giving a better user experience.

I find that sentence "64-bit MSYS2 can be used to build, install and run both 32-bit and 64-bit variants" wrong and/or misleading. Or at least it's not true anymore. Maybe I am missing something and there is a multilib toolchain in msys2?

**Comment by Biswa96** [comment]
I think that 32 bit msys2 section should be removed. 32 bit msys2 installation was deprecated & removed long ago.

**Comment by pedrolcl** [comment]
> You omitted the most important part of that sentence in your quote: "When it comes to native software". The sentence is about developing/using _native_ 32-bit or 64-bit Windows applications and/or libraries. The 64-bit MSYS2 (approx. Cygwin) parts of the MSYS2 project can be used to do that. That is, e.g., the bash and other "low-level" things mostly needed for development.
> 
> MSYS2 software itself is _not_ native Windows. But the MSYS2 project also hosts repositories with packages for native Windows.
> 
> See also here: https://www.msys2.org/docs/environments/

Many/most people installs msys2 just to access and use gcc to build source code on windows. And the page is named "installation", so that people is likely to read this page, and feel betrayed.

**Comment by mmuetzel** [comment]
> Many/most people installs msys2 just to access and use gcc to build source code on windows. And the page is named "installation", so that people is likely to read this page, and feel betrayed.

Hu? Could you please elaborate on why they would feel betrayed?

**Comment by mmuetzel** [comment]
I really wish there were different names for the MSYS2 environment (that is a derivative of Cygwin) and the MSYS2 project as a whole that provides repositories with packages (including compilers) for the different environments. That would probably help to avoid some confusion...

**Comment by lazka** [comment]
> I really wish there were different names for the MSYS2 environment (that is a derivative of Cygwin) and the MSYS2 project as a whole that provides repositories with packages (including compilers) for the different environments. That would probably help to avoid some confusion...

We could rename it to CYGWIN at some point. Not sure if that reduces or increases the confusion though.

**Comment by Biswa96** [comment]
> Not sure if that reduces or increases the confusion though.

User would get confused and reports msys2 issues in cygwin or vice-versa.

**Comment by mmuetzel** [comment]
> We could rename it to CYGWIN at some point. Not sure if that reduces or increases the confusion though.

We should probably ask the Cygwin maintainers first if we converge on that.
If we'd like to point out that it is not *exactly* Cygwin, maybe we could name it somewhat differently. E.g., `CYG64`? That would maybe also allow to avoid confusion with the Cygwin project.

**Comment by lazka** [comment]
yeah, `CYGWINISH` ;)

We could also go some completely different route and name it something like `CORE`, `BASE`, `INTERNAL`, 'DEV' etc.

**Comment by mmuetzel** [comment]
Thinking about it, it might be good if the name of the environment would hint that it is a "(mainly) POSIX-compatible runtime environment that only happens to run on Windows". For people that are familiar with Cygwin, that name (or a similar one) would probably speak for itself. For others, that might be more difficult to convey in one single word.
I keep circling back to something like `CYG64` (that would also hint at it being a 64-bit environment and might be different enough to avoid confusing it with the Cygwin project). Or `POSIXW64`?
