### ISSUE TITLE
Strange NUL file in msys2/tmp/go-build(random numbers) folder that can't be removed

### ISSUE THREAD

**Issue by iocmet** [msys2/msys2.github.io#254]
![image](https://user-images.githubusercontent.com/63492966/215696971-93bc683e-7f18-4779-8236-b78574d6bf52.png)
![image](https://user-images.githubusercontent.com/63492966/215697017-5c45cf39-974d-4e7e-b013-a21b4d22d206.png)
![image](https://user-images.githubusercontent.com/63492966/215697056-e3921448-6983-4f45-932e-e86bf6597c53.png)
![image](https://user-images.githubusercontent.com/63492966/215697193-5805bab0-86f1-4e81-9e37-4d7d9b754c53.png)

**Comment by Biswa96** [comment]
NUL is one of the reserved file names in Windows. More info can be found here https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file. It is not allowed to do any file operation from Windows programs. But it is possible to some file operation with Windows APIs. Hence you can delete or create that NUL file in cygwin or msys2 or git-for-windows.

**Comment by Biswa96** [comment]
So, the question is answered, I guess.
