### ISSUE TITLE
Msys2.org down?

### ISSUE THREAD

**Issue by Ajedi32** [msys2/msys2.github.io#26]
While trying to download MSYS2 from the website I'm getting timeout errors. The msys2.github.io works fine, but [msys2.org](http://msys2.org/) and [repo.msys2.org](http://repo.msys2.org/) are unresposive.

Is this a temporary issue, or maybe just me?

**Comment by MenaceInc** [comment]
Can confirm not just you. Tried contacting via IRC but no answer yet.
