### ISSUE TITLE
pacman -Syu is not starting

### ISSUE THREAD

**Issue by appsheld** [msys2/msys2.github.io#262]
Msys2 installed on windows 11 with msys2-x86_64-20230127.exe

msys2 many times startet:

###################################################################
#                                                                 #
#                                                                 #
#                   C   A   U   T   I   O   N                     #
#                                                                 #
#                  This is first start of MSYS2.                  #
#       You MUST restart shell to apply necessary actions.        #
#                                                                 #
#                                                                 #
###################################################################

Andreas@PC-AD2 MSYS ~
# pacman -Syu

Andreas@PC-AD2 MSYS ~
# pacman -S root

Andreas@PC-AD2 MSYS ~
# pacman-key -l
==> ERROR: You do not have sufficient permissions to read the pacman keyring.
==> Use 'pacman-key --init' to correct the keyring permissions.

Andreas@PC-AD2 MSYS ~
# pacman-key --init
mkdir: cannot create directory ‘’: No such file or directory
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
chmod: cannot access '/trustdb.gpg': No such file or directory
/usr/bin/pacman-key: line 244: ((: >= 0 : syntax error: operand expected (error token is ">= 0 ")

Andreas@PC-AD2 MSYS ~
#

**Comment by Biswa96** [comment]
Did you restart the shell, i.e. close the window and reopen it? Does excluding the msys2 installation directory in Windows Defender help?

**Comment by appsheld** [comment]
** ... msys2 many times startet:**

Defender is disabled.

**Comment by appsheld** [comment]
The Problem is pacman-conf.exe, i can not execute it:

Andreas@PC-AD2 MSYS ~
$  /usr/bin/pacman-conf
bash: /usr/bin/pacman-conf: Permission denied

I have set chmod 777 /usr/bin/pacman-conf.exe, but no change.

Andreas@PC-AD2 MSYS ~
$ ls  -l /usr/bin/pacman-conf
-rwxr-xr-x 1 Andreas Andreas 10800192 Jan 17 22:05 /usr/bin/pacman-conf

My Edition is:	Windows 11 Enterprise
Version	22H2
Systembuild	22623.1325
Windows Feature Experience Pack 1000.22639.1000.0

**Comment by Biswa96** [comment]
Uninstall and reinstall msys2. Make sure to exclude the msys2 installation directory in Windows Defender (as you did earlier).

**Comment by appsheld** [comment]
I have made a feedback in WIN 11 Insider Feedback Hub to tell Microsoft the Problem:  https://aka.ms/AAjtz5h

**Comment by appsheld** [comment]
1. I excluded c:\msys64 in Microsoft Defender
2. I uninstalled msys2
3. I installed msys 2 msys2-x86_64-20230127.exe
4. No change of the problem

Starting msys2 shell:
![Bild1](https://user-images.githubusercontent.com/64687988/221799592-eb7eabdc-7f76-4414-9a03-2fac7eb78f0c.png)

Start complete and some comands:
![image](https://user-images.githubusercontent.com/64687988/221801048-36c53a9b-1b3d-4d55-b9be-53d2e52df2c3.png)

![image](https://user-images.githubusercontent.com/64687988/221801238-1b572985-adbe-4eb4-a5d9-cbd994316d1f.png)

![image](https://user-images.githubusercontent.com/64687988/221801497-6004e58f-ec2e-4caa-b36d-66190698b40a.png)

**Comment by appsheld** [comment]
I have made some modifications in pacman-key script to see what is happening arround line 688:
See "myECHO..."

![image](https://user-images.githubusercontent.com/64687988/221808717-c98707cc-d3a5-46d2-9272-9fb52f485a5b.png)

The output is now:
![image](https://user-images.githubusercontent.com/64687988/221809449-fce45c1f-4d9a-41f0-87b3-518f63d547b7.png)

In my second PC Msys2 works and the output is:
![image](https://user-images.githubusercontent.com/64687988/221810050-888613c1-dc2b-4960-8fea-be0e30524375.png)

PC1 and PC2 have the same Windows Installation. I dont know what makes the difference.

Do you know how i can disable Defender completely? I think MS has disabled this option.

**Comment by appsheld** [comment]
I think the main Problem is pacman-conf.exe:

![image](https://user-images.githubusercontent.com/64687988/221814743-7097bf4a-2fdf-446c-8947-500c3a5630c7.png)

**Comment by Biswa96** [comment]
I can not reproduce the issue in my system. See the following screenshot

![image](https://user-images.githubusercontent.com/31443074/221815549-28aee6c8-50b8-454d-bfb8-4a5cbb497459.png)

Most of the time, this type of random things happen only when Windows Defender or other antivirus software does something weird. I am out of suggestions. Please wait for others.

**Comment by appsheld** [comment]
Thanks for today....

**Comment by appsheld** [comment]
Now I have disabled "Run as administrator" from compatibility of pacman-conf.exe. "Permission denied" is gone, but pacman-conf.exe is not working:
![image](https://user-images.githubusercontent.com/64687988/221845224-a6e3274a-e802-405a-9965-cc312b460a6b.png)

**Comment by appsheld** [comment]
I have made a copy of pacman-conf.exe to pacman-conf2.exe. The copy is working:
![image](https://user-images.githubusercontent.com/64687988/221888322-1114f1d6-df09-454f-9c43-7e745073e62e.png)

**Comment by appsheld** [comment]
The fault was a wrong configuration in MS Defender:

![image](https://user-images.githubusercontent.com/64687988/221911076-3f13d870-7e19-4c26-b137-fb61b6fbe1c6.png)

ACG must be "off" and all others set to "default"
or remove pacman-conf.exe from app-list and all in system-list set to "default"

Solved
![image](https://user-images.githubusercontent.com/64687988/221912621-18626a8b-60d4-4304-9423-3c891bb8dda0.png)
