### ISSUE TITLE
pacman -Syu breaks installer shortcuts

### ISSUE THREAD

**Issue by ezyang** [msys2/msys2.github.io#27]
I don't know if this is the right tracker to report the bug. If not please kindly point me in the right direction.

Steps to reproduce:
1. Download the 64-bit installer and install (with all default settings)
2. Open the MSYS2 shell from the Start Menu and type `pacman -Syu`
3. Close the shell, and try to open it again.

Expected result: It works

Actual results: The shortcuts are broken, with the error:

```
'C:\msys64\msys2_shell.bat' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by ezyang** [comment]
The problem is easy enough to fix manually: just go the containing folder and update the shortcuts to point to `msys.exe`, `mingw32.exe` and `mingw64.exe` in your root installation directory.

**Comment by elieux** [comment]
Not really the right place, but it's probably fine.

This is a known issue. The `filesystem` package (to which these .bat/.cmd files belong) is supposed to show a post-upgrade notice with instructions to change the Start menu shortcuts, but it fails to run when `bash` or `msys2-runtime` is updated beforehand.

The "easy" fix is to release new installers, which we are planning to do, but I think it deserves a better solution -- maybe `filesystem` shouldn't be among the "core" packages at all. What do you think, @renatosilva, @alexpux?

**Comment by Alexpux** [comment]
Fixed in last installer
