### ISSUE TITLE
MSYS2 Site not working

### ISSUE THREAD

**Issue by 8086ware** [msys2/msys2.github.io#274]
Site won't work no matter what I do, throws a 404 error. Is this temporary?
![image](https://user-images.githubusercontent.com/92650801/232186958-ffd9e453-0c57-49e1-b8f2-6dd3a728c3d6.png)

**Comment by Biswa96** [comment]
My mistake. I accidentally deleted the main branch here https://github.com/msys2/msys2.github.io/pull/273. Please wait for the maintainers 🙇

**Comment by Biswa96** [comment]
The website is back online. Would you like to check it please?

**Comment by Biswa96** [comment]
I apologize for my mistake. The website is back online.
