### ISSUE TITLE
mirror.msys2.org is slow

### ISSUE THREAD

**Issue by xobs** [msys2/msys2.github.io#276]
As suggested by https://github.com/msys2/msys2.github.io/blob/source/web/dev/mirrors.md#mirrors I'm reporting that the default mirror of `mirror.msys2.org` is excruciatingly slow. Transfers run at a few tens of kB/s, which make installs take a very long amount of time.

Slow mirrors such as this should be deprioritized.

**Comment by lazka** [comment]
Can you paste the output of:

```
curl -I https://mirror.msys2.org/distrib/msys2-x86_64-latest.exe
```

(so we know which mirrors you get redirected to)

**Comment by xobs** [comment]
Sure:

```
$ curl -I https://mirror.msys2.org/distrib/msys2-x86_64-latest.exe
HTTP/2 302
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
cache-control: private, no-cache
content-type: text/html; charset=utf-8
date: Tue, 18 Apr 2023 08:05:36 GMT
link: <https://repo.extreme-ix.org/msys2/distrib/x86_64/msys2-x86_64-20230318.exe>; rel=duplicate; pri=1; geo=in
location: https://mirror.archlinux.tw/MSYS2/distrib/x86_64/msys2-x86_64-20230318.exe
server: Mirrorbits/v0.5.1-31-geeea0e0-dirty
```

So the URL that is extremely slow is https://repo.extreme-ix.org/msys2/distrib/x86_64/msys2-x86_64-20230318.exe

**Comment by lazka** [comment]
thanks.

(sadly our Singapore mirror is down for the last 3 weeks and they don't respond to emails)

**Comment by lazka** [comment]
I've sent them an email and they are looking into it. I've disabled the mirror redirect for now.

**Comment by lazka** [comment]
I've added a small test to catch such broken mirrors in the future: https://github.com/msys2/msys2-main-server/commit/9e7badbdcd11dd5e2cc3cb937f3fb7a8a17731e6

**Comment by lazka** [comment]
There is nothing more we can do here for now.

If anyone knows a mirror in the India/South-Asia area, let us know.

thanks @xobs for reporting.
