### ISSUE TITLE
Removing of mirror

### ISSUE THREAD

**Issue by smlrrlms** [msys2/msys2.github.io#278]
Hello.

Please remove temporary my repo fastmirror.pp.ua/msys2 from monitoring and site.

I am currently out of storage.

Thanks.

**Comment by lazka** [comment]
ok, thanks for the notice

**Comment by smlrrlms** [comment]
Hello.

I've added some space to my server and now the msys2 repo is operational.

Please add it back to the site.

**Comment by lazka** [comment]
thanks, I'll have a look

**Comment by lazka** [comment]
done, thanks!
