### ISSUE TITLE
Pacman update breaks mingw

### ISSUE THREAD

**Issue by DenisKolodin** [msys2/msys2.github.io#28]
The command `pacman -Sy pacman` changes `pacman 4.x.x` to `pacman 5.x.x`. When I'm trying to execute `pacman -Syu` it fails with:

```
3 [main] pacman (8536) C:\msys64\usr\bin\pacman.exe: *** fatal error - cygheap base mismatch detected - 0x180326400/0x18033A408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version. The most recent version should
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution. Rebooting is also suggested if you
are unable to find another cygwin DLL.
```

**Comment by elieux** [comment]
Hi. So after installing MSYS2, the only command you ran was `pacman -Sy pacman` and that was successful, but after that `pacman -Syu` didn't even start and just showed this error?

**Comment by Alexpux** [comment]
Need first upgrade msys2-runtime, then upgrade pacman. Pacman linked with newer msys-2.0.dll that can contain symbols that not in previous version.

**Comment by DenisKolodin** [comment]
I've followed steps from https://msys2.github.io/
After `msys2-runtime` upgrade everything updates successfully. Thank you!
