### ISSUE TITLE
using msys with windows terminal

### ISSUE THREAD

**Issue by nuitlejour** [msys2/msys2.github.io#282]
I want to use msys2 and other environment from windows terminal, and I find this page from official website:
https://www.msys2.org/docs/terminals/
The problem is the example code only shows GUID for  "UCRT64 / MSYS2" and "MSYS / MSYS2" subsystems,  could you please add example codes for "CLANG64/ MSYS2", "CLANGARM64/ MSYS2", "MINGW64/ MSYS2","MINGW32/ MSYS2"?

**Comment by Biswa96** [comment]
> could you please add example codes for "CLANG64/ MSYS2", "CLANGARM64/ MSYS2", "MINGW64/ MSYS2","MINGW32/ MSYS2"?

You have to just change the ` -ucrt64` option in `commandline` string to `-clang64`, `-clang32` etc. You can get all the valid options with `C:/msys64/msys2_shell.cmd --help` command.

**Comment by nuitlejour** [comment]
> You have to just change the ` -ucrt64` option in `commandline` string to `-clang64`, `-clang32` etc. You can get all the valid options with `C:/msys64/msys2_shell.cmd --help` command.

What about GUID, do I same GUID for all entries?

**Comment by Biswa96** [comment]
>  do I same GUID for all entries?

Just create a new profile from Settings in Windows Terminal. GUIDs will be automatically be added.

**Comment by nuitlejour** [comment]
> > do I same GUID for all entries?
> 
> Just create a new profile from Settings in Windows Terminal. GUIDs will be automatically be added.

Thank you , that worked. 

To be noted:
I am using the lastest terminal,  version 1.17.11461.0, you don't actually need to edit json file manually, instead, just go to Settings -> add a new profile -> command line, input one of the following line without quote:

C:/msys64/msys2_shell.cmd -defterm -here -no-start -ucrt64
C:/msys64/msys2_shell.cmd -defterm -here -no-start -msys
C:/msys64/msys2_shell.cmd -defterm -here -no-start -clang64
C:/msys64/msys2_shell.cmd -defterm -here -no-start -clangarm64
C:/msys64/msys2_shell.cmd -defterm -here -no-start -clang32
C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64
C:/msys64/msys2_shell.cmd -defterm -here -no-start -mingw32

Change appropriate icon for your shortcut, and save.
