### ISSUE TITLE
Request: ARM64 version of libusb

### ISSUE THREAD

**Issue by timmerk** [msys2/msys2.github.io#294]
Hi all, I saw on https://www.msys2.org/wiki/arm64/ that I can request ARM64 versions of packages that don't yet have ARM versions. libusb is one of them, so it would be great if that was added. Thanks!

**Comment by lazka** [comment]
https://packages.msys2.org/package/mingw-w64-clang-aarch64-libusb

**Comment by timmerk** [comment]
Thanks! Not sure how I missed that!

**Comment by timmerk** [comment]
Closing

**Comment by lazka** [comment]
great :)
