### ISSUE TITLE
Missing devel headers in clangarm64

### ISSUE THREAD

**Issue by adaasch** [msys2/msys2.github.io#295]
I tried compiling something for Windows 11 arm64.

I couldn't find some headers like "termios.h" and "sys/mman.h" in the clangarm64 repo.

As adviced I report this here.

**Comment by MehdiChinoune** [comment]
Please report it to mingw-w64/mingw-w64 repo.

**Comment by Biswa96** [comment]
> I couldn't find some headers like "termios.h" and "sys/mman.h" in the clangarm64 repo.

Those are not for cygwin/msys programs, not for native Windows programs. If you want to compile native Windows program those are not required.

If a program requires those header file, you have two options - either port the program to native Windows API or use msys environment.
