### ISSUE TITLE
Issue with pacman in msys2-x86_64-20230718.exe?

### ISSUE THREAD

**Issue by berkidem** [msys2/msys2.github.io#296]
I was following [these instructions](https://code.visualstudio.com/docs/cpp/config-mingw). I had vscode installed, I installed [this version](https://github.com/msys2/msys2-installer/releases/download/2023-07-18/msys2-x86_64-20230718.exe) of msys2, and when I ran:

```
pacman -S --needed base-devel mingw-w64-ucrt-x86_64-toolchain
``` 
(or anything else using pacman) in the automatically opened command window, I got the following response:

```
bash: $'\302\226pacman': command not found
```

I tried to resolve the issue but pacman didn't seem to be available/accessible. I was a bit short on time so I decided to go to an older version to see if that would work. I removed that installation and instead used [the older version](https://github.com/msys2/msys2-installer/releases/download/2023-05-26/msys2-x86_64-20230526.exe) and I was able to complete the process without an issue.

**Comment by MehdiChinoune** [comment]
Please, type `pacman` directly instead of copy/paste or delete the hidden character before p of pacman.

**Comment by Biswa96** [comment]
You typed or copied the command in wrong way. There may be some extra hidden characters.
