### ISSUE TITLE
[Documentation] in docs/environments "UCRT only ships by default on Windows 10" should be updated to include Windows 11 as well

### ISSUE THREAD

**Issue by remon-drk** [msys2/msys2.github.io#305]
In "UCRT" under "MSVCRT vs UCRT" in https://www.msys2.org/docs/environments/ it says:
> It only ships by default on Windows 10 and for older versions you have to provide it yourself or depend on the user having it installed.

This may be misleading as Windows 11 also comes with UCRT https://learn.microsoft.com/en-us/cpp/windows/universal-crt-deployment:
> The Universal CRT (UCRT) is a Microsoft Windows operating system component. It's included as part of the operating system in Windows 10 or later, and Windows Server 2016 or later.

**Comment by Biswa96** [comment]
Thank you for reporting the issue. I have added a pull request to fix the documentation. Would you like to review the change in the aforementioned pull request?
