### ISSUE TITLE
problems with new installer msys2-x86_64-20160921.exe

### ISSUE THREAD

**Issue by mausalimi** [msys2/msys2.github.io#31]
hello,
i'm facing some problems with the newest installer. what i do is
- install msys2-x86_64-20160921.exe
- either do a pacman -S mingw-w64-x86_64-toolchain or a pacman -S mingw-w64-x86_64-gcc

both fail with errors (many of them): 
mingw-w64-x86_64-xxxxxxxxxxx: /mingw64 existiert im Dateisystem

but i don't see a mingw64 on that installation.

the same happens with pacman -S mingw-w64-i686-gcc, there i get mingw-w64-i686-xxxxxxxxxxx: /mingw32 existiert im Dateisystem

that said, i had absolutely no such issue with the older installer, that worked flawlessly with the same instructions.

**Comment by Alexpux** [comment]
Is your MSYS2 installation on disk with NTFS partition?

**Comment by mausalimi** [comment]
yes, this is the case.

/offtopic: this must have been the fastest response i ever got. :)

**Comment by mausalimi** [comment]
uh, that does the trick. simple as that.

sorry for this.

**Comment by selay01** [comment]
I solved the problem by manually creating /mingw32 and /mingw64 directories in windows explorer.
but why the bash give the confused infomation?!!!!!

**Comment by achadwick** [comment]
It's nothing to to with mingw64.exe or mingw64.ini existing, as they indeed do.

Per https://github.com/msys2/msys2.github.io/issues/27#issuecomment-239197035, the `filesystem` package is being omitted in the current installer. I think that's deliberate, but @Alexpux @elieux please confirm.

Installer `msys2-x86_64-20160921.exe` and its current instructions do not install `filesystem`, and this causes problems for users when we tell them to "just" install MSYS2 and "just" the packages we need. Without `filesystem` (or manual creation), `/mingw64` and `/mingw32` don't exist, which causes native installers to fail outright.

Requiring `--force` is IMO not a solution. Please make the instructions match the installer, and let's make the combination deliver a system on which our users can deploy native packages for testing.

**Comment by elieux** [comment]
@achadwick

It's not that `filesystem` is missing, it's that it doesn't contain `/mingw32` and `/mingw64`. The latest `filesystem` package (uploaded to repo) has them, but not the version in the installer.

Existence of these directories will disable the `/mingwXX` `<->` `/mingwXX.exe` [shadowing](https://cygwin.com/cygwin-ug-net/using-specialnames.html#pathnames-exe) and let pacman install everything correctly. Doing `mkdir -p /mingw{32,64}` is definitely a better fix than passing `--force` to pacman.

**Comment by Smasherr** [comment]
This also concerns another mingw64 packages: `mingw-w64-x86_64-libpng`, `mingw-w64-x86_64-SDL_ttf` and `mingw-w64-x86_64-SDL_mixer`. Or even maybe all of them. `mkdir -p /mingw{32,64}` helped me a lot, thanks!

**Comment by elieux** [comment]
Should be fixed now, I hope.
