### ISSUE TITLE
uninstaller wipes contents under junction points instead of deleting the junction

### ISSUE THREAD

**Issue by qnxor** [msys2/msys2.github.io#32]
Luckily I have daily backups, but this just happened: I created a junction for `C:\Users\ME` as `/home/ME` since I already had `.ssh` and other things that are common to many other things (git, cygwin, etc). When I uninstalled msys2 (*), it started deleting recursively the files from all subdirectories, instead of deleting the subdirectory tree. It traversed the junction as well and started deleting everything under C:\Users\ME as well.

I suggest you chanfge the uninstaller's behavior to delete the dir tree rather than travserse it and delete files, in order for junctions to be deleted, rather than the contents the junction points to.

(*) it got broken after an upgrade beyond my patience to repair and I wanted to reinstall it.

**Comment by elieux** [comment]
This issue was moved to msys2/msys2#1
