### ISSUE TITLE
mirror.msys2.org seems down

### ISSUE THREAD

**Issue by ptahmose** [msys2/msys2.github.io#328]
I'm having trouble reaching mirror.msys2.org.

E.g. for https://mirror.msys2.org/?mirrorstats I keep getting ERR_CONNECTION_TIMED_OUT.

**Comment by ognevny** [comment]
it's known issue. please, wait until it's solved

**Comment by ptahmose** [comment]
Thanks for your quick reply! OK, best wishes for fixing the issue.

**Comment by ognevny** [comment]
it's now back online in my browser

**Comment by lazka** [comment]
See https://fosstodon.org/@msys2org/112613760071246157

Thanks for the report.
