### ISSUE TITLE
mirror.selfnet.de doesn't sync

### ISSUE THREAD

**Issue by lazka** [msys2/msys2.github.io#330]
@carrotIndustries hey, we had an outage ~11 days ago, and since then mirror.selfnet.de doesn't seem to sync anymore. Do you have any ideas? thanks!

https://mirror.selfnet.de/msys2/

**Comment by carrotIndustries** [comment]
Thanks for the nudge. Our rsync job apparently got stuck instead of failing so it just sat there doing nothing.

Restarted it, the mirror should be back in sync now.

**Comment by lazka** [comment]
Thanks! confirmed.

In case it isn't already used, adding timeouts might have helped: https://gitlab.archlinux.org/archlinux/infrastructure/-/blob/e53a7897271c8dc8ddc772744a3a1ca48d180894/roles/syncrepo/files/syncrepo-template.sh#L66

**Comment by lazka** [comment]
Since I have no other contact info, misusing this issue:

just a heads up that there are various new rsync vulnerabilities disclosed today, which also affect read-only public rsyncd mirror setups like yours:
https://www.openwall.com/lists/oss-security/2025/01/14/3

In case of Debian, which also updated the protocol version to v31 to v32 as part of the backports, the following should show 32.0 with the fixes in place (replace the domain with your rsync mirror domain):

$  timeout 1 telnet repo.msys2.org 873 | grep @RSYNCD
@RSYNCD: 32.0 sha512 sha256 sha1 md5 md4

**Comment by lazka** [comment]
@carrotIndustries Since I have no other contact info, misusing this issue:

just a heads up that there are various new rsync vulnerabilities disclosed today, which also affect read-only public rsyncd mirror setups like yours:
https://www.openwall.com/lists/oss-security/2025/01/14/3

In case of Debian, which also updated the protocol version to v31 to v32 as part of the backports, the following should show 32.0 with the fixes in place (replace the domain with your rsync mirror domain):

$ timeout 1 telnet repo.msys2.org 873 | grep @rsyncd
@rsyncd: 32.0 sha512 sha256 sha1 md5 md4

**Comment by carrotIndustries** [comment]
Thanks for the heads-up, installed the update.

**Comment by lazka** [comment]
confirmed, thanks!

**Comment by lazka** [comment]
fyi, https://mirror.selfnet.de/msys2/ hasn't synced in 18 days

**Comment by carrotIndustries** [comment]
rsync fails with this message after over an hour after starting:
```
Aug 12 00:29:48 mirror-1 msys2[521525]: [generator] io timeout after 600 seconds -- exiting
Aug 12 00:29:48 mirror-1 msys2[521525]: rsync error: timeout in data send/receive (code 30) at io.c(201) [generator=3.2.7]
```

Our other mirrored projects work just fine, so I think that it's not our storage backend that's causing the timeout.

**Comment by lazka** [comment]
Thanks for having a look!

All the other 13 mirrors are fine, so I'm wondering what's special here, hmm. I need to check out the logs

**Comment by lazka** [comment]
looks like it fixed itself somehow.

The 600 seconds is likely the idle timeout we have set on the server (in theory it shouldn't trigger due to keepalive). I'll try to bump that if it happens again.

**Comment by carrotIndustries** [comment]
Ah, that might explain it: I did some experimentation and got it to work by removing the `--temp-dir=/tmp` option. Copying files from `/tmp` to the cephs mount sometimes was really slow and therefore most likely tripped the server-side idle timeout as no data was transferred during that period.
