### ISSUE TITLE
Uninstall??

### ISSUE THREAD

**Issue by ayaen** [msys2/msys2.github.io#331]
No FAQ. No where obvious in documentation. No obviously named binaries. Clicking on the uninstall shortcut takes me to Windows Settings Apps List, but obviously nothing shows up. This is not expected of you people.
Google has nothing on this. 

Please tell me I am wrong. Tell me there is a section somewhere I can read about removing this software.
I appreciate your work, but do not, at all, understand your _need_ to make this so hard, so needlessly hard.
I need to reclaim drive space,and clean up my windows system. So msys2 has to go, for now.

But maybe I am thinking I will never install this again since you've made it so difficult already.

**Comment by ayaen** [comment]
I don't know why this makes me so sad and angry. Please understand where I am coming from when I opened this issue. I do not mean to pollute your development space with such negative talk, but I find it very disappointing that an open=source software cannot gracefully uninstall itself from the system the user installed it on.

**Comment by lazka** [comment]
It should be possible to uninstall it like every other Windows application in the apps list:

![image](https://github.com/user-attachments/assets/4b5ca426-2b3c-4693-ad04-9c7f5202ea15)

**Comment by Ruebled** [comment]
There is an uninstall.exe in the installation folder of the application:
![image](https://github.com/user-attachments/assets/aff9d4a1-2dda-472b-bc76-189a621ff354)

or as user @lazka mentioned in the previous comment.
