### ISSUE TITLE
Is it possible to add Visual C++ as a toolchain?

### ISSUE THREAD

**Issue by felixf4xu** [msys2/msys2.github.io#336]
Hi,

When I read https://www.msys2.org/docs/environments/ and found that gcc and llvm(clang) are the only 2 toolchains, I can't help but wonder why visual c++ can't be one of them?

**Comment by Biswa96** [comment]
> I can't help but wonder why visual c++ can't be one of them?

You can use Microsoft Visual Studio toolchain with vscode. Then, you do not need to use msys2.

**Comment by felixf4xu** [comment]
but in that case, I will miss `pacman`. pacman can **install** packages directly, for visual studio I need to manually **compile** and install.

**Comment by Biswa96** [comment]
Please feel free to do as you wish, but kindly refrain from mixing MinGW and MSVC libraries.
