### ISSUE TITLE
error: target not found: mingw-w64-python-pre-commit

### ISSUE THREAD

**Issue by winterz** [msys2/msys2.github.io#342]
According to https://packages.msys2.org/base/mingw-w64-python-pre-commit there is a package for pre-commit.

yet:
```
> pacman -S mingw-w64-python-pre-commit
error: target not found: mingw-w64-python-pre-commit
```

not sure what I'm doing wrong.

**Comment by Biswa96** [comment]
mingw-w64-python-pre-commit is not an actual package name. See the "Binary Packages" list below in that web page.
