### ISSUE TITLE
cython LONG_BIT (bad gcc/glibc config?)

### ISSUE THREAD

**Issue by frustaci** [msys2/msys2.github.io#350]
Experimenting with cython in msys2 for the first time im running into this issue

cython test.py
gcc -Wall -I/usr/include/python3.12 -I/usr/include test.c -o test.exe

D:/msys64/usr/include/python3.12/pyport.h:586:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  586 | #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."

**Comment by lazka** [comment]
are you using the matching gcc? /usr/bin/gcc

**Comment by frustaci** [comment]
i think so, im on ucrt64 prompt and i dont have python or cython or gcc in windows path

**Comment by lazka** [comment]
If you are targeting ucrt64 then you have the wrong python, `pacman -S mingw-w64-ucrt-x86_64-python mingw-w64-ucrt-x86_64-cython`

`/usr/include` is cygwin stuff

**Comment by frustaci** [comment]
Indeed /ucrt64/include works.
Though then i ran into a ton of Python related linker errors for which adding the libpython3.11 in ucrt64/lib didnt seem to make any difference.
Anyway im ok wih cythonize for now so i can skip all these compilation quirks.

**Comment by frustaci** [comment]
eventually got it working with:
cython -a --embed --cplus file.cpp
g++ -O2 -Wall -municode -I/ucrt64/include/ -I/ucrt64/include/python3.12 -L/ucrt64/lib file.cpp -lpython3.12 -o file.exe

closing this.
