### ISSUE TITLE
fastmirror.pp.ua mirror not accessible from Russia

### ISSUE THREAD

**Issue by void2012** [msys2/msys2.github.io#352]
I have manually cleared the fastmirror.pp.ua URLs from pacman mirrorlists but still stumbling on errors such as 

> error: failed retrieving file 'mingw-w64-i686-tk-8.6.13-1-any.pkg.tar.zst' from mirror.msys2.org : Failed to connect to fastmirror.pp.ua port 443 after 10000 ms: Could not connect to server

All of Ukrainian servers IPs are banned in Russia. I have no VPN. What should I do?

**Comment by Biswa96** [comment]
You have to edit every /etc/pacman.d/mirrorlist files to comment the fastmirror.pp.ua URL. Then `pacman -Syu`.

**Comment by void2012** [comment]
I did. Every single file. Deleted all the lines with that URL

**Comment by Biswa96** [comment]
The URL is redirected from mirror.msys2.org. So, comment that also.

**Comment by void2012** [comment]
It worked, thanks!
