### ISSUE TITLE
GDB ignores Y/N prompts

### ISSUE THREAD

**Issue by anikom15** [msys2/msys2.github.io#39]
This is done in an MSYS shell.
Steps to reproduce:
Here is the hello program:
#include <stdio.h>

int main()
{
        printf("Hello, world!\n");
        return 0;
}
cc -g -o hello.exe hello.c
gdb hello.exe
Type 'b main' to set a breakpoint.
Type 'r' to run.
Type 'q' to quit.
$ gcc -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-6.3.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 6.3.0 (Rev1, Built by MSYS2 project)

$ ld -v
GNU ld (GNU Binutils) 2.27

**Comment by Alexpux** [comment]
GDB 7.12 is broken. You can download 7.11-4 from expository manually and downgrade it while current GDB not fixed

**Comment by elieux** [comment]
This issue was moved to msys2/msys2#2
