### ISSUE TITLE
Can't link dynamic MPFR

### ISSUE THREAD

**Issue by stackTom** [msys2/msys2.github.io#44]
I have successfully built static 32 and 64 bit GNU GMP, MPFR, and MPC on Windows 10 and have been able to use these libraries in Visual Studio 2019.

However, when building dynamically, GMP will build and work correctly (I make sure libgmp-10.dll is in my PATH and that I link against libgmp.dll.a). But, I can't get MPFR to link correctly, whether 32 or 64 bit. As an example, for 32 bit, I place libmpfr-6.dll (output of mpfr build in bin/) in my PATH and link against libmpfr.dll.a (output of mpfr build in lib/). I also place libgcc_s_dw2-1.dll from mingw32/bin in my PATH as I get a popup asking for it. However, then I get the error "The procedure entry point mpfr_add could not be located in the dynamic link library C:\Users\devel\source\repos\ConsoleApplication2\Debug\ConsoleApplication2.exe.

I've tried to make sure that my mingw32/bin is the first thing in PATH in visual studio, I've tried copying over libstd-c++-6.dll and libwinpthrea-1.dll from mingw32/bin to the folder where the executable is running, but I am unsuccessful.

Any ideas?

Edit:

Please delete. I will repost this in the appropriate repo. Did not realize this was for the website.

**Comment by lazka** [comment]
> Please delete. I will repost this in the appropriate repo. Did not realize this was for the website.

No problem, github also allows us to move issues if needed.
