### ISSUE TITLE
32-bit (yes, I saw the commit)

### ISSUE THREAD

**Issue by Logics4** [msys2/msys2.github.io#47]
496d5ef :eyes: 

For moments I got scared that I wouldn't be able to reinstall MSYS2 because the 32-bit download wasn't in the front page anymore. I got around it though :P
Maybe you could just put a big warning sign on the website and keep the download under some sort of legacy category?

**Comment by lazka** [comment]
So you are using 32bit Windows?

**Comment by Logics4** [comment]
> So you are using 32bit Windows? Can you maybe expand a bit on why? (just curious..)

I've got a low-end computer with Windows 7 x86 and 2GB of RAM; my CPU is an Athlon 64 +3800, but I'm sure that if it ran a 64-bit OS things would probably be slower as it'd require a bigger amount of memory.

Also I've got an old onboard graphics unit (ATI Radeon Xpress 200) which doesn't receive driver updates nowadays - maybe not relevant but it's just to show that this thing is old already.

It has served me for probably 4 years? It was bought used, and currently I have no financial means of upgrading my hardware, so that's why I've stuck with it. It's not the best thing one could use but so far I've been able to play some games, do my academic work and have some little programming projects of mine as a hobby. And that's why I use MSYS2 and why the 32-bit version is useful for me still.

**Comment by lazka** [comment]
Thanks for the insight, I'll think about it.

**Comment by Logics4** [comment]
Alright 👍

**Comment by lazka** [comment]
I'm afraid we've hit various problems with the 32bit build that we decided to no longer build any new packages for 32bit msys (32 bit mingw continues as usual) since we lack the manpower to fix them.

This means the installer will still work but you wont get any new package updates. Since that is a potential security risk I don't think it's a good idea to advertise this on the main page anymore.

**Comment by lazka** [comment]
For future reference this is the last installer we released: https://github.com/msys2/msys2-installer/releases/tag/2020-05-17

The 32bit repo will continue to exist for now.

**Comment by Logics4** [comment]
Alright, thank you for answering.
