### ISSUE TITLE
Shell cannot source files

### ISSUE THREAD

**Issue by kugel-** [msys2/msys2.github.io#5]
Hello,

when running /bin/sh or /bin/dash -c ". foo", the file can't be sourced. Instead I get "/bin/sh: line 0: .: foo: file not found". The same does not happen if I spell /bin/bash explicitly, even though /bin/sh *is* bash (md5sum matches).

This breaks scripts that rightfully use . to source in plain shell scripts.

**Comment by Alexpux** [comment]
This is not right place for such issues. This is only for github site itself.
Use https://github.com/Alexpux/MSYS2-packages
