### ISSUE TITLE
"Latest" MSYS downloads are not latest

### ISSUE THREAD

**Issue by orlp** [msys2/msys2.github.io#53]
http://repo.msys2.org/distrib/ contains various 'latest' downloads which are not in fact the latest. I'm not sure if this is the right place to open this issue, but I figured the website repo would be.

**Comment by elieux** [comment]
Should be resolved tomorrow. :)

**Comment by orlp** [comment]
Great, thanks.

**Comment by lazka** [comment]
At least the latest one is there now.
