### ISSUE TITLE
pacman -Syu fails to update -- error: key could not be looked up remotely

### ISSUE THREAD

**Issue by AMDphreak** [msys2/msys2.github.io#67]
Don't know if this is a bug or a support request, and don't care, because it looks like a bug either way:
```
$ pacman -Syu
:: Synchronizing package databases...
 mingw32               468.8 KiB   153 MiB/s 00:00 [#####################] 100%
 mingw32.sig           119.0   B  0.00   B/s 00:00 [#####################] 100%
 mingw64               471.4 KiB   153 MiB/s 00:00 [#####################] 100%
 mingw64.sig           119.0   B  0.00   B/s 00:00 [#####################] 100%
 msys                  189.8 KiB  92.7 MiB/s 00:00 [#####################] 100%
 msys.sig              438.0   B  0.00   B/s 00:00 [#####################] 100%
error: msys: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
:: Import PGP key 4A6129F4E4B84AE46ED7F635628F528CF3053E04? [Y/n] Y
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: failed to update msys (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases
```

Also cannot work around this by using the official Windows installer:
![image](https://user-images.githubusercontent.com/1058978/88457307-eac67d80-ce4a-11ea-9371-5dee2d578a5c.png)

**Comment by lazka** [comment]
https://www.msys2.org/news/#2020-06-29-new-packagers

**Comment by AMDphreak** [comment]
> https://www.msys2.org/news/#2020-06-29-new-packagers

Thank you. 

I'm closing this. I uninstalled msys2 and am trying to reinstall with choco, unsuccessfully. This transitional information doesn't appear to be prominently displayed on the main page. Not sure what you can do but everyone with this problem should not have to post an issue and waste your time reading it and posting a link.

**Comment by lazka** [comment]
> This transitional information doesn't appear to be prominently displayed on the main page.

I've added something now. Thanks for the suggestion.

**Comment by franko** [comment]
I will try to reinstall MSYS2 from scratch to fix this signatures fiasco.

The instructions in the news page are incomplete and confused. I tried to follow them and it didn't work.

Please respect more your users.

I was thinking about recommending MSYS2 to my colleagues but after this accident I will probably abstain.

**Comment by Biswa96** [comment]
If you install using the new installer you don't have to follow the instructions in that news.

**Comment by franko** [comment]
This is what I have just done, I have wiped the old install and reinstalled everything from scratch. Then configured again my bash environment and installed again all the packages I need.

**Comment by rurban** [comment]
All recipes fail on appveyor, the most popular Windows CI platform.

curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz times out

```
rm -r /etc/pacman.d/gnupg/
pacman-key --init
pacman-key --populate msys2
```
fails to install 4A6129F4E4B84AE46ED7F635628F528CF3053E04

Sample log: https://ci.appveyor.com/project/rurban/safeclib/builds/35612191/job/28lek4tw79nfnsy0

**Comment by lazka** [comment]
The 2019 appveyor image should have an update MSYS2 which no longer needs the keyring workaround

**Comment by jrajasekaran** [comment]
Im trying to move to 2.6.3 from 2.6.6, since the Timers.group is not functioning as expected in 2.6.6, Unable to do because of the mingw installation issue. Any guidance will be helpful.

**Comment by R030t1** [comment]
I'm encountering this, is there a fix? Most of the search results I turn up are for CI usage and they blow away the install.
