### ISSUE TITLE
Download links do not work

### ISSUE THREAD

**Issue by eduard93** [msys2/msys2.github.io#8]
From http://msys2.github.io/
Links to download 
http://repo.msys2.org/distrib/i686/msys2-i686-20150916.exe
http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20150916.exe
Fail

**Comment by mingwandroid** [comment]
I cannot reproduce this.

**Comment by eduard93** [comment]
Sorry, my bad. Turns out, disk was full.
