### ISSUE TITLE
Installation fails on Windows Server 2019 Core due to missing OPENGL32.dll

### ISSUE THREAD

**Issue by andy-schmidt** [msys2/msys2.github.io#81]
I am trying to setup a build server with Msys2 and the Mingw-w64 compiler on a Windows Server Core 2019 instance. However, when I try to run the installer, it fails because of a missing dependency on `OPENGL32.dll`. Please see the attached screenshot.
![NoOPENGL32-dll](https://user-images.githubusercontent.com/6588961/94495442-9f13b580-01a6-11eb-890b-e88b6a3a7c7c.PNG)

This is a rather strange requirement to install a `bash` command line environment.

Is there a why to silently install Msys2 without the OpenGL dependency?

**Comment by jeremyd2019** [comment]
https://github.com/msys2/msys2-installer/releases/download/2020-07-20/msys2-base-x86_64-20200720.sfx.exe ? (or newer versions)

**Comment by andy-schmidt** [comment]
That works. Thank you for the prompt response, I really appreciate it!
