### ISSUE TITLE
Download not available for msi installer

### ISSUE THREAD

**Issue by AMDphreak** [msys2/msys2.github.io#86]
![image](https://user-images.githubusercontent.com/1058978/95025407-22be1e00-064f-11eb-8ebf-c7d59e3e4cda.png)

**Comment by mathacka** [comment]
Same, it's not working now and it didn't work yesterday either, repository is timing out.

**Comment by jeremyd2019** [comment]
msys2/MSYS2-packages#2171

**Comment by lazka** [comment]
It's back online now. Sorry!
