### ISSUE TITLE
Should be available on msys2.org

### ISSUE THREAD

**Issue by achadwick** [msys2/msys2.github.io#9]
Please could this site be made available on http://msys2.org and http://www.msys2.org? All I get when I go there is an empty file tree.
- Docs: https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

We did something like this in a hurry for `mypaint.org` and `www.mypaint.org` [when our old provider went dark](https://github.com/mypaint/mypaint/issues/496) and it works really well in practice:
- See https://github.com/mypaint/mypaint.github.io and its [CNAME](https://github.com/mypaint/mypaint.github.io/blob/master/CNAME) file.
- Relevant DNS records:
  - `www.mypaint.org.   300 IN  CNAME   mypaint.org.`  
  - `mypaint.org.       300 IN  A   192.30.252.153`  
  - `mypaint.org.       300 IN  A   192.30.252.154`

The CNAME change needs to be coordinated with the DNS switchover.

**Comment by elieux** [comment]
Took me a good while to understand what's the actual request here. You want the `msys2.github.io` site to be hosted on `msys2.org` instead, right?

I'm not opposed to this, at least until we can get some proper content into the CMS that's running there at the moment. @alexpux, @mingwandroid?

**Comment by achadwick** [comment]
No, that's not what I'm asking. In the absence of a proper site at whatever that host is, as a user I would like the download/intro page that currently appears at <https://msys2.github.io/>, which looks like

![Screenshot of msys2.github.io at the current time](https://cloud.githubusercontent.com/assets/61299/12063582/006b48d4-afa9-11e5-9652-6f98fcba8de5.png)

to appear at `http://msys2.org` instead. This would be more immediately useful to new users than a blank file browser, and allow me to give out a much more professional-looking link when I'm referring people to the MSYS2 project.

At the moment, the introductory material is a blank CMS :confused:, something useful :tada: but on a weird-looking .github.io address :disappointed:, and a bunch of docs on (, ugh,) _Sourceforge_ :imp:. I'm suggesting getting rid of the blank CMS initially to make the picture look a little less rotten.

Ultimately I would like to see the end of Sourceforge anything for the project.

Doing the CNAME thing and still hosting on github.io would allow you guys to use Jekyll if you want a CMS, or just host static HTML with JS as now. It's up to you, but Jekyll is kinda nice.

**Comment by elieux** [comment]
Heh. That's exactly what I thought you were proposing and what I thought I wrote down in my last post, but apparently the terminology is confusing to both of us.

Now that we know what is the proposition and we see the reasons (I mostly agree with what you said in your last post), let's wait for an executive decision.

**Comment by perlun** [comment]
:+1: on this one, it seems weird to just have a placeholder site there when we actually have something much more useful. It should just be a matter of adding a `CNAME` file, and update the DNS.

**Comment by mkae** [comment]
I'd also be in favor of moving away from SF! 

That was indeed a little showstopper for me as a new user, since my Firefox' ublock plugin wouldn't want to let me browse the wiki for a start. I had to give it special permission to go there. The plugin malware list knew about SF and thus recommended to reconsider what I was browsing for... I might not be the only potential user who was close to be driven away from even trying out this project because of just that!!!

**Comment by Alexpux** [comment]
We have run site on msys2.org but it just empty now. When we have time we move everything there

**Comment by achadwick** [comment]
@Alexpux 
IMO, the simplest and quickest thing would be to repoint the DNS records (while ensuring that `repo.msys2.org` doesn't break, naturally). The project would gain a useful, non-SourceForge, bug tracker for the splash site too.

It would be wonderful for me if the project could relocate its activity to [the github msys2 organization](https://github.com/msys2/) too. Purely because the name is great, and it should be seen as more than one person :smile:

**Comment by greatwolf** [comment]
msys2.org now just tives me a 503 bad gateway.

**Comment by elieux** [comment]
Done! We'll maybe revert to a custom site later, but the GitHub-hosted webpage is now at www.msys2.org.
